---
title: "Py-learning"
author: "xsl"
date: "2020/12/21"
output: html_document
---
# Python Learnin

## 相关论坛及参考网站

- [stack overflow](https://stackoverflow.com/)

- [V2EX](https://www.v2ex.com)

- Google

- [segmentfault（中文）](https://segmentfault.com)

- [啄木鸟社区](https://woodpecker.org.cn/)

- [水木社区](https://www.newsmth.net/bbsdoc.php?board=Python)

- [入门Python有什么好的书籍推荐](https://www.zhihu.com/answer/449361926)

- [学习python有什么奥德视频教程](https://www.zhihu.com/answer/1071270537)

## 就业方向

1. **Web应用开发**

服务器端编程，具有丰富的Web开发框架，如Django和TurboGears，迅速完成一个网站的开发和Web服务。

2. 系统网络运维

在运维的工作中，有大量重复性工作的地方，并需要做管理系统、监控系统、发布系统等，将工作自动化起来，提高工作效率，这样的场景Python是一门非常合适的语言。

3. **科学与数字计算**

Python被广泛的运用于科学和数字计算中，例如生物信息学、物理、建筑、地理信息系统、图像可视化分析、生命科学等。

4. 3D游戏开发
Python有很好的3D渲染库和游戏开发框架，有很多使用Python开发的游戏，如迪斯尼卡通城、黑暗之刃。

5. 图形界面开发

Python可编写桌面图形用户界面，还可以扩展微软的Windows，常用Tk、GTK+、PyQt、win32等。

6. 网络编程

除了网络和互联网的支持，Python还提供了对底层网络的支持，有易于使用的Socket接口和一个异步的网络编程框架Twisted Python。

## 入门学习

### 学习大纲

1. Python基础知识和高级特性

- Python语法基础

- Python字符串解析

- thon时间和日历

- Python文件操作

- Python面向对象

- 并发编程

- 函数式编程

- 正则表达式

- 设计模式

- 排序算法

- 异常

- 模块

2. Linux基础

1、shell操作
2、系统管理
3、常用Linux命令
4、常见Linux系统
5、HDFS搭建

3. 数据库原理和sql优化

1、Linux下MySQL数据库
2、数据库设计和SQL标准
3、Python数据库操作的库
4、Linux下MongoDB非关系型数据库
5、SQL优化和数据库优化
6、ORM对象关系映射基本思想

4. 前端web开发

1、Html
2、CSS
3、PC端页面开发实战流程
4、Bootstrap
5、html5和css3
6、JQuery


5. Python web后端开发

1、Django 框架开发
2、Nginx配置和uWSGI部署
3、RESTful接口开发
4、Flask框架开发
5、电商平台项目
6、BBS论坛系统

6. 爬虫和数据分析

1、第一个Python网络爬虫
2、专业HTTP分析工具Fiddler的使用
3、实际爬虫Python编码问题
4、urllib2 的使用TesseractOCR语言模型爬取使用带验证码登录的网站
5、Beautiful Soup
6、XPath & CSS选择器
7、PhantomJS
8、SeleniumWebdriver
9、Scrapy大型框架使用代理服务器爬取
10、Scrapy分布式集群多代理爬虫Redis
11、分布式集群Redis MongoDB在爬虫里的应用
12、数据分析工具与模块


7. Python人工智能

1、机器学习
2、深度学习


### 学习重点

第一阶段：专业核心基础

阶段目标：

1. 熟练掌握Python的开发环境与编程核心知识

2. 熟练运用Python面向对象知识进行程序开发

3. 对Python的核心库和组件有深入理解

4. 熟练应用SQL语句进行数据库常用操作

5. 熟练运用Linux操作系统命令及环境配置

6. 熟练使用MySQL，掌握数据库高级操作

7. 能综合运用所学知识完成项目

知识点：

Python编程基础、Python面向对象、Python高级进阶、MySQL数据库、Linux操作系统。

1、Python编程基础，语法规则，函数与参数，数据类型，模块与包，文件IO，培养扎实的Python编程基本功，同时对Python核心对象和库的编程有熟练的运用。

2、Python面向对象，核心对象，异常处理，多线程，网络编程，深入理解面向对象编程，异常处理机制，多线程原理，网络协议知识，并熟练运用于项目中。

3、类的原理，MetaClass，下划线的特殊方法，递归，魔术方法，反射，迭代器，装饰器，UnitTest，Mock。深入理解面向对象底层原理，掌握Python开发高级进阶技术，理解单元测试技术。

4、数据库知识，范式，MySQL配置，命令，建库建表，数据的增删改查，约束，视图，存储过程，函数，触发器，事务，游标，PDBC，深入理解数据库管理系统通用知识及MySQL数据库的使用与管理。为Python后台开发打下坚实基础。

5、Linux安装配置，文件目录操作，VI命令，管理，用户与权限，环境配置，Docker，Shell编程Linux作为一个主流的服务器操作系统，是每一个开发工程师必须掌握的重点技术，并且能够熟练运用。

第二阶段：PythonWEB开发

阶段目标：

1. 熟练掌握Web前端开发技术，HTML，CSS，JavaScript及前端框架

2. 深入理解Web系统中的前后端交互过程与通信协议

3. 熟练运用Web前端和Django和Flask等主流框架完成Web系统开发

4. 深入理解网络协议，分布式，PDBC，AJAX，JSON等知识

5. 能够运用所学知识开发一个MiniWeb框架，掌握框架实现原理

6. 使用Web开发框架实现贯穿项目

知识点：

Web前端编程、Web前端高级、Django开发框架、Flask开发框架、Web开发项目实战。

1、Web页面元素，布局，CSS样式，盒模型，JavaScript，JQuery与Bootstrap掌握前端开发技术，掌握JQuery与BootStrap前端开发框架，完成页面布局与美化。

2、前端开发框架Vue，JSON数据，网络通信协议，Web服务器与前端交互熟练使用Vue框架，深入理解HTTP网络协议，熟练使用Swagger，AJAX技术实现前后端交互。

3、自定义Web开发框架，Django框架的基本使用，Model属性及后端配置，Cookie与Session，模板Templates，ORM数据模型，Redis二级缓存，RESTful，MVC模型掌握Django框架常用API，整合前端技术，开发完整的WEB系统和框架。

4、Flask安装配置，App对象的初始化和配置，视图函数的路由，Request对象，Abort函数，自定义错误，视图函数的返回值，Flask上下文和请求钩子，模板，数据库扩展包Flask-Sqlalchemy，数据库迁移扩展包Flask-Migrate，邮件扩展包Flask-Mail。掌握Flask框架的常用API，与Django框架的异同，并能独立开发完整的WEB系统开发。

第三阶段：爬虫与数据分析

阶段目标：

1. 熟练掌握爬虫运行原理及常见网络抓包工具使用，能够对HTTP及HTTPS协议进行抓包分析

2. 熟练掌握各种常见的网页结构解析库对抓取结果进行解析和提取

3. 熟练掌握各种常见反爬机制及应对策略，能够针对常见的反爬措施进行处理

4. 熟练使用商业爬虫框架Scrapy编写大型网络爬虫进行分布式内容爬取

5. 熟练掌握数据分析相关概念及工作流程

6. 熟练掌握主流数据分析工具Numpy、Pandas和Matplotlib的使用

7. 熟练掌握数据清洗、整理、格式转换、数据分析报告编写

8. 能够综合利用爬虫爬取豆瓣网电影评论数据并完成数据分析全流程项目实战

知识点：

网络爬虫开发、数据分析之Numpy、数据分析之Pandas。

1、爬虫页面爬取原理、爬取流程、页面解析工具LXML，Beautifulfoup，正则表达式，代理池编写和架构、常见反爬措施及解决方案、爬虫框架结构、商业爬虫框架Scrapy，基于对爬虫爬取原理、网站数据爬取流程及网络协议的分析和了解，掌握网页解析工具的使用，能够灵活应对大部分网站的反爬策略，具备独立完成爬虫框架的编写能力和熟练应用大型商业爬虫框架编写分布式爬虫的能力。

2、Numpy中的ndarray数据结构特点、numpy所支持的数据类型、自带的数组创建方法、算术运算符、矩阵积、自增和自减、通用函数和聚合函数、切片索引、ndarray的向量化和广播机制，熟悉数据分析三大利器之一Numpy的常见使用，熟悉ndarray数据结构的特点和常见操作，掌握针对不同维度的ndarray数组的分片、索引、矩阵运算等操作。

3、Pandas里面的三大数据结构，包括Dataframe、Series和Index对象的基本概念和使用，索引对象的更换及删除索引、算术和数据对齐方法，数据清洗和数据规整、结构转换，熟悉数据分析三大利器之一Pandas的常见使用，熟悉Pandas中三大数据对象的使用方法，能够使用Pandas完成数据分析中最重要的数据清洗、格式转换和数据规整工作、Pandas对文件的读取和操作方法。

4、matplotlib三层结构体系、各种常见图表类型折线图、柱状图、堆积柱状图、饼图的绘制、图例、文本、标线的添加、可视化文件的保存，熟悉数据分析三大利器之一Matplotlib的常见使用，熟悉Matplotlib的三层结构，能够熟练使用Matplotlib绘制各种常见的数据分析图表。能够综合利用课程中所讲的各种数据分析和可视化工具完成股票市场数据分析和预测、共享单车用户群里数据分析、全球幸福指数数据分析等项目的全程实战。

第四阶段：机器学习与人工智能

阶段目标：

1. 理解机器学习相关的基本概念及系统处理流程

2. 能够熟练应用各种常见的机器学习模型解决监督学习和非监督学习训练和测试问题，解决回归、分类问题

3. 熟练掌握常见的分类算法和回归算法模型，如KNN、决策树、随机森林、K-Means等

4. 掌握卷积神经网络对图像识别、自然语言识别问题的处理方式，熟悉深度学习框架TF里面的张量、会话、梯度优化模型等

5. 掌握深度学习卷积神经网络运行机制，能够自定义卷积层、池化层、FC层完成图像识别、手写字体识别、验证码识别等常规深度学习实战项目

知识点：

1、机器学习常见算法、sklearn数据集的使用、字典特征抽取、文本特征抽取、归一化、标准化、数据主成分分析PCA、KNN算法、决策树模型、随机森林、线性回归及逻辑回归模型和算法。熟悉机器学习相关基础概念，熟练掌握机器学习基本工作流程，熟悉特征工程、能够使用各种常见机器学习算法模型解决分类、回归、聚类等问题。

2、Tensorflow相关的基本概念，TF数据流图、会话、张量、tensorboard可视化、张量修改、TF文件读取、tensorflow playround使用、神经网络结构、卷积计算、激活函数计算、池化层设计，掌握机器学习和深度学习之前的区别和练习，熟练掌握深度学习基本工作流程，熟练掌握神经网络的结构层次及特点，掌握张量、图结构、OP对象等的使用，熟悉输入层、卷积层、池化层和全连接层的设计，完成验证码识别、图像识别、手写输入识别等常见深度学习项目全程实战。

### 入门书籍

- Python3 标准库

对程序员而言，标准库与语言本身同样重要，它能为各种常见的任务提供完美的解决方案，所以本书是所有Python程序员都必备的**工具书**！全书**以案例驱动的方式讲解了标准库中数百个模块的使用方法（如何工作）和工作原理（为什么要这样工作）**，比标准库的官方文档更容易理解，为Python程序员熟练掌握和使用这些模块提供了绝佳指导。

- Python学习手册 第4版

是**Python入门必读之作**，位列美亚软件编程畅销榜首，《Python编程》姊妹篇，详细讲解各种语言特性。本书全面、系统讲解Python语言核心知识，每个知识都会以知识点、思想、示例代码的方式详细展开，由浅入深，循序渐进。无论你从事哪个领域，本书都为你提供了未来全部Python工作的必备知识。

- Effective Python：编写高质量Python代码的59个有效方法

以使用**场景**为主导的精练教学方式，汇聚了59条优秀的实践原则、开发技巧和便捷方案，并以实用的代码范例来解释它们。通过本书，你能够了解到解决关键编程任务所用的最佳方式，并学会编写易于理解、便于维护且利于改进的代码。

- Python程序设计（原书第2版）

本书介绍Python的基础知识，旨在帮助学生首先掌握概念，之后通过步骤完备的**实例**培养学生的问题求解能力。这一版采用**Python3**，并对全书结构进行了优化，既可**作为入门**程序设计课的入门教材**，也可供Python爱好者自学参考。

### 入门视频跟学

1. 一个月完成了python从入门到精通，B站最强学习路线

2. 

3. 10个python完整小项目教你爬虫+数据分析+数据可视化

- python数据分析教程（1800分钟）《利用python进行数据分析》

- 600集python从入门都精通

- 


### 学习顺序

## 深入学习