---
title: "supply-chain management"
author: "向树林"
date: "2020/12/13"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

# 例14-3

1. **已知条件：**

- T = 4周

- L = 1周

- $UPS_1=0.66+0.26x$

- $D_H \sim N(2,5)$,   $D_L \sim N(20,5)$

- CML=0.997

- $单位重量m_H=0.1,m_L=0.04,库存持有成本费率h=0.25,单位成本C_H=200,C_L=30$

> 综上：考察周期盘点下的安全库存，再加分散与聚集策略


2. **解题：**

- **原方案**

原方案为周期订货H和L两种产品，T=4，L=1。

$总成本TC_原=年库存持有成本H_原+年运输成本tc_原$

年库存持有成本：$H_原=H_H+H_L=库存持有成本费率*(H总库存*H单位成本+L总库存*L单位成本)=h*(TQ_H*C_H+TQ_L*C_L)$

$TQ_H=24个仓库*(H周转库存+H安全库存)=24*(\frac{Q_H}{2}+ss_H)=24*(\frac{T\mu_H}{2}+F_s^{-1}(CML)*\sigma_H*\sqrt{T+L})$

由Excel得出：$NORMSINV(0.997)=2.7478, \sqrt{5}=2.2361$

因此：$TQ_H=24*(\frac{4*2}{2}+2.7478*5*\sqrt{4+1})=24*(4+30.7)=832.8(台)$

同理，$TQ_L=24*(\frac{4*20}{2}+2.7478*5*\sqrt{4+1})=24*(40+30.7)=1696.8(台)$

所以：$H=H_H+H_L=0.25*(832.8*200+1696.8*30)=54366(美元)$


每个地区每周期运输成本：$tc_{T原}=tc_{H原}+tc_{L原}=0.66+0.26*(0.1*Q_H+0.04*Q_L)=0.66+0.26*(0.1*8+0.04*80)=1.7(美元)$

年运输成本：$tc_原=24*13*tc_{T原}=530(美元)$

综上：原方案总成本$TC_原=54366+530=54896(美元)$

- **方案A：** $T=4 \Rightarrow T=1$

变动的量：

$ss_H、ss_L、H周转库存、L周转库存 \rightarrow 年库存持有成本(H_H、H_L)$

由计算器得出：$\sqrt{2}=1.4142$

所以方案A的年库存持有成本$H_A=H_{HA}+H_{LA}=0.25*[(200*24*(\frac{1*2}{2}+2.7478*5*\sqrt{1+1}))+(30*24*(\frac{1*20}{2}+2.7478*5*\sqrt{1+1}))]=0.25*[(200*490.3)+(30*706.3)]=29812(美元)$

$T \rightarrow 年运输成本(13 \rightarrow 52)$

所以方案A的年运输成本$tc_A=24*52*tc_{TA}=24*52*[0.66+0.26*(0.1*1*2+0.04*1*20)]=1148(美元)$

综上：方案A总成本$TC_A=H_A+tc_A=29812+1148=30960(美元)$

- **方案B(聚集策略)：** $仓库数量=24 \Rightarrow 仓库数量=1, T=4 \Rightarrow T=1,UPS_2=5.53+0.53x$

> Note:假设工厂所在地为大仓库，即不考虑工厂到大仓库的运输费用

由计算器得出：$\sqrt{6}=2.4495$

方案B年库存持有成本$H_B=H_{HB}+H_{LB}=0.25*[(200*(24*\frac{1*2}{2}+2.7478*\sqrt24*5*\sqrt{1+1}))+(30*(24*\frac{1*20}{2}+2.7478*\sqrt24*5*\sqrt{1+1}))]=0.25*[200*(24*1+2.7478*2*2.4495*5*1.4142)+30(24*10+2.7478*2*2.4495*5*1.4142)]=0.25*[200*119.2+30*335.2]=8474(美元)$

方案B年运输费用(一个周期运输2次)$tc_B=2*52*tc_{TB}=2*52*24*[5.53+0.53*(0.1*1+0.04*10)]=14464(美元)$

综上：方案B总成本$TC_B=H_B+tc_B=8474+14464=22938(美元)$

综上所述：原方案总成本为54896美元，方案A总成本30960美元，方案B总成本22938美元，因此HighMed公司应该选择方案B。


# 例16-6

1. **已知条件**

- $Q \sim N(10,4)$

- $P_1=10000, P_2=12500$

2. **解题**

假设该制造商应该为Q运输能力签订长期批量合同

单位超触成本:$C_u=12500-10000=2500$

单位欠储成本：$C_o=10000$

根据报童模型：$F(Q^*)=\frac{C_u}{C_u+C_o}=\frac{2500}{2500+10000}=0.2$

由Excel得：$NORMSINV(0.2)=-0.84162$

签订长期批量合同的最优运输能力$Q^*=F^{-1}_s(\frac{C_u}{C_u+C_o})*\sigma+\mu=F^{-1}_s(0.2)*4+10=-0.84162*4+10=6.63352(百万单位)$

综上：制造商应该为6.6352百万单位的运输能力签订长期批量合同。




